project_name: gosimports
changelog:
  skip: true
builds:
  - id: gosimports
    main: ./cmd/gosimports/
    ldflags: -s -w -X main.version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - s390x
      - ppc64le
    ignore:
      - goos: darwin
        goarch: s390x
      - goos: darwin
        goarch: ppc64le
      - goos: windows
        goarch: s390x
      - goos: windows
        goarch: ppc64le
brews:
  - name: gosimports
    tap:
      owner: rinchsan
      name: homebrew-tap
    url_template: "https://github.com/rinchsan/gosimports/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    folder: Formula
    homepage: "https://pkg.go.dev/github.com/rinchsan/gosimports/cmd/gosimports"
    description: Command gosimports updates your Go import lines, adding missing ones, removing unreferenced ones, and removing redundant blank lines.
    test: |
      system "#{bin}/gosimports --help"
    install: |
      bin.install "gosimports"
